### ISSUE TITLE
Regarding attribute get_symbol() in Onsitepotential.py

### ISSUE THREAD

**Issue by AnandoUS** [WMD-group/MacroDensity#1]
Hi,

When I tried using the code OnSitePotential.py it didn't work. It gave the error atom has no attribute get_symbol().

I had to modify the code slightly to make it run. I used get_chemical_symbols instead. The following is the modified code

coords = ase.io.vasp.read_vasp(coordinate_file)
scaled_coords = coords.get_scaled_positions()
symbols = coords.get_chemical_symbols()
ox_coords = []
i = -1

for atom in coords:
    i = i + 1
    if symbols[i] == species:
       print symbols[i]
       ox_coords.append(scaled_coords[i])
  
Hope this helps anyone trying to use it.

**Comment by keeeto** [comment]
Hi,

Thanks for letting us know! This is related to an outdated call to ASE. I will update in the code as you did.

Thanks again,

Keith
