### ISSUE TITLE
How to plot MacroDensity/tutorials/HeteroJunction/HJ.png?

### ISSUE THREAD

**Issue by Shuyangzero** [WMD-group/MacroDensity#18]
Hi

Your plot of HJ.png is so coool! Could you please tell me how to plot that? Thanks!

**Comment by keeeto** [comment]
Sorry for such a late response :) That was made with `vesta` - opening an geometry file of that heterojunction, https://jp-minerals.org/vesta/en/doc.html

**Comment by keeeto** [comment]
Closed!
