### ISSUE TITLE
Macroscopic Average Potential

### ISSUE THREAD

**Issue by lediaz** [WMD-group/MacroDensity#20]
Hello, I am trying to plot the macroscopic average potential using the PlanarAverage.py script but I am not getting the correct average. For instance, the planar average will oscillate and after running the PlanarAverage.py that oscillation will be replaced by a flat line. Could anyone help me with this? 

I am trying to create the plot in https://github.com/Anower120/MacroDensity/blob/master/tutorials/HeteroJunction/HeteroJunction.ipynb
with the Planar and Macroscopic averages.

**Comment by keeeto** [comment]
Hello - can you send some more details about the nature of the issue. It would help to see some of the plots that you are creating and what is wrong with them. Thanks.

**Comment by keeeto** [comment]
Seems dead
