### ISSUE TITLE
unable to install through pip

### ISSUE THREAD

**Issue by spnana** [WMD-group/MacroDensity#21]
I am using a MAC OS and with the following command 
pip3 install git+git://github.com/WMD-group/MacroDensity.git
I get this error: 
Collecting git+git://github.com/WMD-group/MacroDensity.git
  Cloning git://github.com/WMD-group/MacroDensity.git to /private/var/folders/m7/7c68by855bq5bn4p89v0jj880000gp/T/pip-req-build-227v2sb0
ERROR: Command errored out with exit status 128: git clone -q git://github.com/WMD-group/MacroDensity.git /private/var/folders/m7/7c68by855bq5bn4p89v0jj880000gp/T/pip-req-build-227v2sb0 Check the logs for full command output.

**Comment by aronwalsh** [comment]
Solved
