### ISSUE TITLE
IndexError when running macrodensity.py

### ISSUE THREAD

**Issue by ericwwelch314** [WMD-group/MacroDensity#22]
Hello,

When trying attempting to analyze my LOCPOT file, after running macrodensity.py and PlanarAverage.py, I get the following error: 

Traceback (most recent call last):
  File "/home/eww9/bin/AvgCharg", line 16, in <module>
    vasp_pot, NGX, NGY, NGZ, Lattice = md.read_vasp_density(input_file)
  File "/gpfs/home/eww9/bin/macrodensity.py", line 306, in read_vasp_density
    Potential[k + m] = inp[m]
IndexError: index 1741825 is out of bounds for axis 0 with size 1741824

I attempted to set NGX, NGY and NGZ in my INCAR file and did a single point calculation (NSW=0) with a converged WAVECAR but this didn't fix the issue.  Has anyone else had this issue and resolved it??

**Comment by aronwalsh** [comment]
This has been updated in the latest version
